language: python
sudo: true
dist: trusty
python:
  - "3.6"
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
    on_failure: change
    on_success: never
install:
  - make travis-sysdeps
env:
  global:
    - PATH=/snap/bin:$PATH
    - CONJUREUP_REGISTRY_BRANCH=master
before_script:
  - sudo addgroup lxd || true
  - sudo usermod -a -G lxd $USER || true
  - sudo ln -s /snap/bin/juju /usr/bin/juju
  - sudo ln -s /snap/bin/lxc /usr/bin/lxc
script:
  - tox -e py36,flake,isort
  - tox -e conjure-dev
  - sudo -E su $USER -c "source conjure-dev/bin/activate && conjure-up --notrack --noreport battlemidget/ghost localhost test-controller test-model"
after_failure:
  - cat ~/.cache/conjure-up/ghost/steps/*/*.err
  - cat ~/.cache/conjure-up/conjure-up.log
  - cat ~/.cache/conjure-up/ghost/*.err
