language: python
sudo: true
dist: trusty
python:
  - "3.6"
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
    on_failure: change
    on_success: never
install:
  - make travis-sysdeps
env:
  global:
    - PATH=/snap/bin:$PATH
    - CONJUREUP_REGISTRY_BRANCH=master
before_script:
  - sudo addgroup lxd || true
  - sudo usermod -a -G lxd $USER || true
script:
  - tox -e py36,flake,isort
  - snapcraft
  - sudo snap install ./conjure-up*.snap
  - sudo -E su $USER -c "lxc finger"
  - sudo -E su $USER -c "lxd init --auto"
  - sudo -E su $USER -c "lxc network create lxdbr0 ipv4.nat=true ipv4.address=auto ipv6.nat=false ipv6.address=none"
  - sudo -E su $USER -c "/snap/bin/conjure-up -d --notrack --noreport ghost localhost test-controller test-model"
after_script:
  - cat ~/.cache/conjure-up/conjure-up.log
  - cat ~/.cache/conjure-up/ghost/*.err
  - cat ~/.cache/conjure-up/ghost/steps/*.err
