name: conjure-up
version: 2.1.0
summary: Package runtime for conjure-up spells
description: >
   This package provides conjure-up, an interface to installing spells that
   provide the user with an end to end walkthrough experience for installing and
   using big software.
confinement: classic
grade: stable

apps:
  conjure-up:
    command: conjure-up-wrapper
  juju:
    command: bin/juju
  bridge:
    command: bridge.start
    stop-command: bridge.stop
    restart-condition: never
    daemon: oneshot

parts:
  conjure:
    plugin: python
    source: .
    requirements: requirements.txt
    stage-packages:
      - bsdtar
      - jq
    stage:
      - -usr/bin/2to3-3.5
      - -usr/bin/py3clean
      - -usr/bin/py3compile
      - -usr/bin/pydoc3.5
      - -usr/share/dh-python
      - -usr/share/python3/py3versions.py
  conjure-configs:
    plugin: dump
    source: .
    filesets:
      etc/conjure-up.conf: etc/conjure-up.conf
  conjure-up:
    plugin: dump
    source: snapcraft/script
    after: [lxd, lxc, lxcfs]
  juju:
    source-tag: juju-2.0.2
    prime:
      - bin/juju
